version: '3'

volumes:
  postgres_volume:

services:
  storage:
    image: postgres:16.1
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    env_file:
      - deploy/env/.env.prod
    ports:
      - "${PG_PORT}:${PG_PORT}"
    command: -p ${PG_PORT}

  redis:
    image: redis:7.2.4
    restart: always
    env_file:
      - deploy/env/.env.prod
    expose:
      - "${REDIS_PORT}"
    command: --port ${REDIS_PORT}


  migrator:
    build:
      dockerfile: deploy/dockerfiles/migrator.Dockerfile
    env_file:
      - deploy/env/.env.prod
    depends_on:
      - storage
    environment:
      PG_HOST: storage

  app:
    build:
      context: .
      dockerfile: deploy/dockerfiles/banner.Dockerfile
    env_file:
      - deploy/env/.env.prod
    depends_on:
      - storage
      - redis
    environment:
      PG_HOST: storage
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
      - "${SWAGGER_PORT}:${SWAGGER_PORT}"
    restart: on-failure